# tasks file for kibana_role
---
  - name: Upload tar.gz Kibana from control node
    copy:
      src: "{{ kibana_package }}"
      dest: "/tmp/kibana-{{ kibana_version }}-linux-x86_64.tar"
    register: get_kibana
    until: get_kibana is succeeded
    tags: kibana
  - name: Create directrory for Kibana
    become: true
    file:
      state: directory
      path: "{{ kibana_home }}"
    tags: kibana
  - name: Extract Kibana in the installation directory
    become: true
    unarchive:
      copy: false
      src: "/tmp/kibana-{{ kibana_version }}-linux-x86_64.tar"
      dest: "{{ kibana_home }}"
      extra_opts: [--strip-components=1]
      creates: "{{ kibana_home }}/bin/kibana"
    tags:
      - skip_ansible_lint
      - kibana
  - name: Set environment Kibana
    become: yes
    template:
      src: templates/kibana.sh.j2
      dest: /etc/profile.d/kibana.sh
    tags: kibana
